### ISSUE TITLE
Sanitize output to remove passwords

### ISSUE THREAD

**Issue by eugene-og** [ordergroove/check_mariadb_slaves#9]
Make error messages appear with sanitized passwords, such as

`CRITICAL - Slave sql is not running. Last error: Error Operation CREATE USER failed for user@127.0.0.1 on query. Default database: . Query: CREATE USER user@127.0.0.1 IDENTIFIED BY *****`

**Comment by juannyG** [comment]
I'll be using the following syntax patterns described in the MariaDB docs that reference password setting:
* [Set Password](https://mariadb.com/kb/en/library/set-password/)
* [Alter user](https://mariadb.com/kb/en/library/alter-user/) which is the same as [Create user](https://mariadb.com/kb/en/library/create-user/)
